"""link alarms to catalog definitions

Revision ID: 324cbf6bcaee
Revises: bce6ca374ddd
Create Date: 2026-09-03 18:15:55.424444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '324cbf6bcaee'
down_revision: Union[str, Sequence[str], None] = 'bce6ca374ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('alarm_definition_id', sa.Integer(), nullable=True))
    op.add_column('alarms', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('alarms', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('unique_active_alarm_definition', 'alarms', ['alarm_definition_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND alarm_definition_id IS NOT NULL"))
    op.create_foreign_key(
        None,
        "alarms",
        "alarm_definitions",
        ["alarm_definition_id"],
        ["id"],
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alarms', type_='foreignkey')
    op.drop_index('unique_active_alarm_definition', table_name='alarms', postgresql_where=sa.text("status = 'ACTIVE' AND alarm_definition_id IS NOT NULL"))
    op.alter_column('alarms', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alarms', 'raw_payload')
    op.drop_column('alarms', 'alarm_definition_id')
    # ### end Alembic commands ###
