"""add machine_id to alarms

Revision ID: a394c1e99de3
Revises: a4bbb80d5834
Create Date: 2026-08-13 21:04:28.627093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a394c1e99de3'
down_revision: Union[str, Sequence[str], None] = 'a4bbb80d5834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('machine_id', sa.Integer(), nullable=False))
    op.create_foreign_key('alarms_machine_id_fkey', 'alarms', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alarms_machine_id_fkey', 'alarms', type_='foreignkey')
    op.drop_column('alarms', 'machine_id')
    # ### end Alembic commands ###
