"""add alarms table

Revision ID: a4bbb80d5834
Revises: 2f5a19d1cf49
Create Date: 2026-08-11 19:07:26.097038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bbb80d5834'
down_revision: Union[str, Sequence[str], None] = '2f5a19d1cf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLVED', name='alarm_status'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Add unique index
    op.create_index(
        'unique_alarms_sensor_code_active',
        'alarms',
        ['sensor_id', 'error_code'],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # drop unique index
    op.drop_index('unique_alarms_sensor_code_active', table_name='alarms')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    # ### end Alembic commands ###

