"""añadir catalogo de alarmas raw

Revision ID: bce6ca374ddd
Revises: a394c1e99de3
Create Date: 2026-09-03 14:20:18.869398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce6ca374ddd'
down_revision: Union[str, Sequence[str], None] = 'a394c1e99de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_alarm_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('alarm_code', sa.String(), nullable=False),
    sa.Column('alarm_name', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_alarm_id', name='uq_alarm_definitions_external_alarm_id'),
    sa.UniqueConstraint('machine_id', 'alarm_code', name='uq_alarm_definitions_machine_code')
    )
    op.create_index('ix_alarm_definitions_machine_tag', 'alarm_definitions', ['machine_id', 'tag_id'], unique=False)
    op.add_column('machines', sa.Column('external_id', sa.String(), nullable=True))
    op.alter_column('machines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_machines_external_id'), 'machines', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_external_id'), table_name='machines')
    op.alter_column('machines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('machines', 'external_id')
    op.drop_index('ix_alarm_definitions_machine_tag', table_name='alarm_definitions')
    op.drop_table('alarm_definitions')
    # ### end Alembic commands ###
